version: '3.8'

services:
  gpt-vis-api:
#    image: apconw/gpt-vis-api:0.0.1
    image: crpi-7xkxsdc0iki61l0q.cn-hangzhou.personal.cr.aliyuncs.com/apconw/gpt-vis-api:0.0.1
    container_name: gpt-vis-api
    ports:
      - "3100:3000"
    environment:
      MINIO_ENDPOINT: host.docker.internal
      MINIO_PORT: 19200
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: gOTrJZGg9T03kb804inP
      MINIO_SECRET_KEY: gLapxVyPECXGvRnDFx7Xr8TXXtWxUtRiBIDkKxrK
      MINIO_BUCKET: chart-images
      MINIO_PUBLIC_DOMAIN: "http://localhost:19200"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    # 添加 volumes 配置，将本地 index.js 挂载到容器内对应位置
    volumes:
      - ./src/index.js:/usr/src/app/src/index.js

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: chart-minio
    ports:
      - "19200:9000"
      - "19201:9001"
    volumes:
      - ./volume/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    command: server /data --console-address ":9001"