version: '3.8'

services:
  gpt-vis-api:
    image: gpt-vis-api:0.0.1
    container_name: gpt-vis-api
    ports:
      - "3100:3000"
    environment:
      MINIO_ENDPOINT: 127.0.0.1
      MINIO_PORT: 19000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: xxx
      MINIO_SECRET_KEY: xxx
      MINIO_BUCKET: chart-images
      MINIO_PUBLIC_DOMAIN: ""
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    # 添加 volumes 配置，将本地 index.js 挂载到容器内对应位置
    volumes:
      - ./src/index.js:/usr/src/app/src/index.js
  
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    ports:
      - "19000:9000"
      - "19001:9001"
    volumes:
      - ./volume/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    command: server /data --console-address ":9001"